services:
  wc_local:
    image: warped-citadel-ui:local
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      - "5173:5173"
  wc_dev:
    image: warpedcitadel/warped-citadel-ui:dev
    ports:
      - "5173:5173"