name: Build test and deploy to DEV

on:
  push:
    branches: [ "test-develop" ]
  pull_request:
    branches: [ "test-develop" ]

jobs:
  test-and-verify:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Build Validation
        run: npm run build

  build-and-push-docker:
    needs: test-and-verify
    runs-on: ubuntu-24.04
    if: github.ref == 'refs/heads/test-develop' && github.event_name == 'push'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: actions/setup-buildx-action@v3

      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: |
            ${{secrets.DOCKER_USERNAME}}/warped-citadel-ui:dev
          cache-from: type=gha
          cache-to: type=gha,mode=max